[general]
import = ["~/.config/alacritty/themes/spacehawk-dark.toml"]

[window]
opacity = 0.98
padding = {x = 10, y = 10}
decorations = "None"

[font]
normal = { family = "VictorMono NF", style = "Regular" } 
size = 14
